version: '3'

services:
  web:
    build: ./service/api
    command: python main.py run -h 0.0.0.0
    volumes:
      - ./service/api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
